# Generated by Django 2.2 on 2021-04-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210405_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='uniqueId',
        ),
    ]
