# Generated by Django 2.2 on 2021-04-28 08:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_mcqset_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectiveSet',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('level', models.CharField(default='Easy', max_length=10)),
                ('answer_keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('subject_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Topic')),
            ],
        ),
    ]
